# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors:
  base-image:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

jobs:
  build:
    executor: base-image
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle clean build -x test

      - persist_to_workspace:
          root: build
          paths:
            - bootJarMainClassName
            - libs
            - tmp
  test:
    executor: base-image
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - attach_workspace:
          at: build
      # run tests!
      - run: gradle test

      - store_test_results:
          path: ./build/test-results/test

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test:
          requires:
            - build